### PR TITLE
Add Tutorial Modules

### PR DESCRIPTION
**Pull request by gilrosenthal**
Just adding the Tutorial Modules for future use. Let me know if I did anything wrong

### CODE REVIEW

**Comment by WesJD** [comment]
Two problems:
1. Point should be in the filters/regions package (create it)
2. You should not have 

```
/**
 * Created by gilar on 5/1/2016.
 */
```

but what is in [LICENSE.txt](LICENSE.txt). If you are using IntelliJ, you can always set up a copyright profile for the project and it will do it automatically.

**Comment by gilrosenthal** [comment]
Fixed

**Comment by WesJD** [comment]
This is a little pesky, but please format it the same as the ones already in the code.

```
/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2016 Wesley Smith
 *
 * Permission is hereby granted, free from charge, to any person obtaining a copy
 * from this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies from the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions from the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
```

**Comment by gilrosenthal** [comment]
Oops, looks like I pushed a bit of Terrain modules too. Sorry for all of the pushes, im super bored today

**Pull request merged**
